version: '3'
services:
  web:
    image: 'demo:latest'
    build: .
    container_name: demo-app
    expose:
      - 8080
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/demodb

  db:
    image: 'postgres:13.1-alpine'
    container_name: demo-db
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=demodb
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data: